### PR TITLE
Layer_15.html

### PR DESCRIPTION
**Pull request by Jorio1984**

### CODE REVIEW

**Review by burgerpunk — CHANGES_REQUESTED** [review]
Move the header tag <h2> CONTENT </h2> above the text (this is the title of the layer). I will correct the template file as well. Otherwise this looks good. Then I will merge.

**Comment by burgerpunk** [comment]
I will change the order in your file myself this time. Updated the template so that others do not make the same mistake

**Comment by burgerpunk** [comment]
Also please name it layer_XX.html I will also add this to the guide.

**Comment by Jorio1984** [comment]
Thanks, obviously i have no idea how this website works.

**Pull request merged**
